### ISSUE TITLE
Tests fails on App Center CI

### ISSUE THREAD

**Issue by mikecann** [Haskkor/react-native-pincode#16]
Hey,

We are trying to use react-native-pincode on AppCenter and are running into an issue. If you setup a simple project that uses react-native-pincode then write a Unit test such as:

```
it('renders without crashing', () => {
   const rendered = renderer.create(<SetPinCodeScreen
     setPinCode={ store }
      />).toJSON();
  expect(rendered).toBeTruthy();
});
```

Then you get the following error:

```
FAIL src/views/set-pin-code/SetPinCodeScreen.test.tsx
  ● Test suite failed to run

    /Users/vsts/agent/2.136.1/work/1/s/node_modules/@haskkor/react-native-pincode/dist/index.js:37
        async componentWillMount() {
              ^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      1 | import * as React from 'react';
      2 | import PINCode, { IProps } from '@haskkor/react-native-pincode'
    > 3 | import { StyleSheet } from "react-native";
        |                         ^
      4 | 
      5 | interface Props extends IProps {
      6 |   id?: string

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/views/set-pin-code/SetPinCodeScreen.tsx:6:17)
```

I looked into that method:

```
async componentWillMount() {
    await AsyncStorage.getItem(this.props.timePinLockedAsyncStorageName || timePinLockedAsyncStorageNameDefault).then((val) => {
      this.setState({pinLocked: !!val})
    })
  }
```

I think maybe AsyncStorage is hanging?

Any thoughts, are you running this on a CI?

**Comment by mikecann** [comment]
Ye you are right, mocking async storage is probably the way to go. thanks!
